name: 🚫 Revoke Developer Certificate
description: Please use the Developer Portal (https://developers.kernelsu.org) to request revocation. This template is auto-filled by the portal.
labels: ["revoke"]
body:
  - type: markdown
    attributes:
      value: |
        ## Revoke Developer Certificate

        > **💡 Recommended:** Please use the [Developer Portal](https://developers.kernelsu.org) to request revocation. The portal will automatically fill this form for you.

        Use this form to request revocation of a developer certificate.

        **Common reasons for revocation:**
        - 🔓 Private key has been compromised
        - 🔑 Private key has been lost
        - 🔄 Certificate is being replaced (superseded)

  - type: input
    id: username
    attributes:
      label: GitHub Username
      description: Your GitHub username (without @)
      placeholder: username
    validations:
      required: true

  - type: input
    id: serial_number
    attributes:
      label: Certificate Serial Number
      description: The serial number of the certificate to revoke (found in your certificate issuance comment)
      placeholder: "1a2b3c4d5e6f7890abcdef1234567890"
    validations:
      required: true

  - type: dropdown
    id: reason
    attributes:
      label: Revocation Reason
      description: Why are you requesting this revocation?
      options:
        - Compromised
        - Lost
        - Superseded
        - Other
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Additional Details
      description: Please provide any additional context or information
      placeholder: Optional details about the revocation request...
    validations:
      required: false

  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Acknowledgments
      description: Please confirm
      options:
        - label: I confirm that I am the owner of this certificate or have authorization to request its revocation
          required: true
